### ISSUE TITLE
Perhaps tag a release?

### ISSUE THREAD

**Issue by mdorman** [mhayashi1120/Emacs-wgrep#26]
The package is obviously stable, since it hasn't been altered in a while.  The latest version on marmalade was 2.1.3.  Perhaps simply tag the current content as 2.1.10, and allow melpa-stable to pick it up?

**Comment by DamienCassou** [comment]
please, that would be useful to me too. Thanks

**Comment by DamienCassou** [comment]
You can do it through github in the "releases" tab or through `git tag`. Thanks

**Comment by mhayashi1120** [comment]
Thanks for the issue. I'm very sorry for the late response.

I don't understand yet how to work melpa-stable for multiple packages. (e.g. wgrep-ag, wgrep-pt)
I add a new tag and will see how it goes.

I am not using stable, so if you become aware of something, please tell me it.

Thanks again for your interest in my program.

**Comment by DamienCassou** [comment]
Thanks

**Comment by mdorman** [comment]
You can see at stable.melpa.org that it picked up the five packages just fine.

Thanks so much.
