### ISSUE TITLE
Text is read-only error

### ISSUE THREAD

**Issue by pallix** [mhayashi1120/Emacs-wgrep#27]
When searching with `ack-menu`, a buffer in `ack-mode` pops up ; when pressing `C-c C-p` and then editing text I get this error : "Text is read-only".

I had another try where I could edit the text but saving didn't work.

It seems the integration with ack is a bit buggy, or am I doing something wrong?

**Comment by pallix** [comment]
Ok it works with the original `ack` mode but not with `ack-menu`.

**Comment by thierryvolpiatto** [comment]
Pierre Allix <notifications@github.com> writes:

> Ok it works with the original ack mode but not with ack-menu.

Don't know what is ack-menu or ack-mode, but it works perfectly with
all helm greps (included ack).

-- 
Thierry

**Comment by mhayashi1120** [comment]
I don't enough know about `ack-menu`, it is not yet supported.
If you could create patch to support that package, feel free to send pull-request or feature request.
Close the issue for the present.

Thanks.
