### ISSUE TITLE
broken compatibility with Ag.el

### ISSUE THREAD

**Issue by jasonm23** [mhayashi1120/Emacs-wgrep#30]
Ag has recently updated the default format of the search result output, and groups file lines under a single heading.

This breaks compatibility with Wgrep, so wgrep-ag will need patching.

Added a note to the relevant commit  on Ag.el https://github.com/Wilfred/ag.el/commit/192422bdee8887d26f9926c72a8109f5806182d6#diff-60680ffddce95e7b6ade86dd5ca068eaR53

@wilfred @albertodonato I hope you guys can help too.

**Comment by jasonm23** [comment]
@mhayashi1120 - is it ~~possible~~ simple, given the current implementation of wgrep to match a group of lines as per the updated **wilfred/ag.el** - see below.

Original ungrouped result form

![original result form](https://cloud.githubusercontent.com/assets/71587/17361694/48203b94-59a4-11e6-9e2c-12d2f2329df9.png)

New, grouped, result format

![screen shot 2016-08-03 at 6 05 08 pm](https://cloud.githubusercontent.com/assets/71587/17361812/e3a852d6-59a4-11e6-84ff-48611f3242a7.png)

**Comment by gambo** [comment]
Came across this and found a quick work around.
Place the following in ~/.emacs or similar.

`(setq ag-arguments '("--smart-case" "--noheading" "--nobreak" "-F"))`

We set the ag arguments to make sure the output is as close to grep as possible.

- We leave smart case on
- disable combined results file headings
- and no newlines
- the "-F" is for grep compatibility

I havent had time to dig in and write a patch, this just gets me by in the meantime.

**Comment by DamienCassou** [comment]
I confirm the problem.

**Comment by NicolasPetton** [comment]
I confirm the issue too.

**Comment by mhayashi1120** [comment]
Very sorry for the late response everyone. Please try this version.
And thanks for your interest to this program.
