### ISSUE TITLE
Time for release

### ISSUE THREAD

**Issue by DamienCassou** [mhayashi1120/Emacs-wgrep#33]
The last stable version of this package is from 2014 (2.1.10): https://stable.melpa.org/#/wgrep. Could you please tag the latest commit so that melpa stable is updated?

Thanks

**Comment by Alexander-Shukaev** [comment]
Agreed.  Is there any showstopper for this?

**Comment by DamienCassou** [comment]
Ping :-). The last release is from 2014.

**Comment by sten0** [comment]
2.3.0 has been released, I think this bug can be closed.

**Comment by DamienCassou** [comment]
thank you
