### ISSUE TITLE
wgrep-helm stopped working

### ISSUE THREAD

**Issue by renatofdds** [mhayashi1120/Emacs-wgrep#34]
After finished editing, i'm getting the reject overlay on every change with the reason property of "File does not exist". wgrep on  `rgrep` works fine.

**Comment by thierryvolpiatto** [comment]
Renato F <notifications@github.com> writes:

> After finished editing, i'm getting the reject overlay on every change
> with the reason property of "File does not exist". wgrep on rgrep
> works fine.

Indeed, this is due to recent changes in helm, I sent a PR fixing this.

Thanks for catching this.

--
Thierry
Gpg Key fingerprint = 6CEC 7081 AB33 E251 4AB8  5FC2 28D1 7F53 59F2 9997
