### ISSUE TITLE
[feature request] add support for ripgrep

### ISSUE THREAD

**Issue by stardiviner** [mhayashi1120/Emacs-wgrep#43]
ripgrep is really fast after some weeks usage. Now I switched to `ripgrep`.
Hope to support `ripgrep`.

**Comment by thierryvolpiatto** [comment]
stardiviner <notifications@github.com> writes:

> ripgrep is really fast after some weeks usage. Now I switched to ripgrep.
> Hope to support ripgrep.

Helm support ripgrep and BTW wgrep from helm is working with RG.


-- 
Thierry

**Comment by stardiviner** [comment]
@thierryvolpiatto  How to invoke wgrep in helm-do-grep-ag results?

**Comment by thierryvolpiatto** [comment]
stardiviner <notifications@github.com> writes:

> @thierryvolpiatto How to invoke wgrep in helm-do-grep-ag results?

First you save the results with C-x C-s, then from the saved buffer you
run M-x wgrep-change-to-wgrep-mode.

-- 
Thierry
Gpg Key fingerprint = 6CEC 7081 AB33 E251 4AB8  5FC2 28D1 7F53 59F2 9997

**Comment by stardiviner** [comment]
Thanks.
