### ISSUE TITLE
Version tag 2.3.1 is missing

### ISSUE THREAD

**Issue by Ambrevar** [mhayashi1120/Emacs-wgrep#64]
2.3.1 does not appear on the release page.

**Comment by sten0** [comment]
@Ambrevar, to my eyes it looks like 2.3.1 hasn't been released because the master branch declares this:
https://github.com/mhayashi1120/Emacs-wgrep/blob/379afd89ebd76f63842c8589127d66096a8bb595/wgrep.el#L7

@mhayashi1120, would you please resolve #65 before tagging `2.3.1`?
