### ISSUE TITLE
Please clarify description and copyright, and also include a full-text copy of the GPL-3+

### ISSUE THREAD

**Issue by sten0** [mhayashi1120/Emacs-wgrep#65]
Hi!

Thank you for maintaining this software :-)  I'm investigating packaging it for Debian, because Ivy/Counsel/Swiper now depends on it (https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=944986).

For the full 205 word writeup, please see that ITP (Intent to Package) bug.  In point form:

1. Please note Matsushita Akihisa's 2002-2009 copyright in the relevant files.
2. Please make your copyright explicit.
3. Please include a full-text copy of the GPL-3+ for this multi-file (and multi ELPA package) work.  Conventionally it's renamed to something like COPYING, COPYRIGHT, or LICENSE.  For your convenience, here is the URL: https://www.gnu.org/licenses/gpl-3.0.txt  GNU prefers `COPYING` and the full guide is available here: https://www.gnu.org/licenses/gpl-howto.html
4. Please enhance the description so that potential users can figure out what advantages wgrep has over `M-x replace-regexp`

I would be happy to help with any of these points.  Help with (4) would require discussion, because I don't yet know how to describe wgrep's full power/usefulness.

Sincerely,
Nicholas

**Comment by sten0** [comment]
P.S. it would also be nice to have a note of what version of grep-edit.el wgrep forked from :-)

**Comment by sten0** [comment]
@mhayashi1120 gentle ping on this issue, because I'd like it to be resolved before 2020

**Comment by mhayashi1120** [comment]
I read this issue today. Very sorry for the late response.
I was going away from Emacs recently, so please wait several days.

**Comment by mhayashi1120** [comment]
> Please enhance the description so that potential users can figure out what advantages wgrep has over M-x replace-regexp

@sten0 Please tell me, where to describe the point?

Surely you have mentioned, `Interactive sed` is a right description, I think.

```
Like `sed` interactively. No need to learn sed script, just learn Emacs.
```

**Comment by sten0** [comment]
Masahiro Hayashi <notifications@github.com> writes:

> I read this issue today. Very sorry for the late response.
> I was going away from Emacs recently, so please wait several days.
>

Thanks!  Sorry it took me so long to follow-up.  My inbox exploded while
I was on holidays and I'm only recently starting to catch up.

**Comment by sten0** [comment]
Hi,

>> Please enhance the description so that potential users can figure out
>> what advantages wgrep has over M-x replace-regexp
>
> @sten0 Please tell me, where to describe the point?
>

I would recommend README.md, after the one line description, and before
§Install.  If you'd like I'd be happy to submit a PR of my best guess.

> Surely you have mentioned, `Interactive sed` is a right description, I think.
>
> ```
> Like `sed` interactively. No need to learn sed script, just learn Emacs.
> ```

That's a nice conclusion sentence for the introduction paragraph (the
long description) :-)

What I mean is something that communicates the advantages over other
Emacs pattern editing facilities like `replace-regexp` and
`query-replace`.

This seems like a small and unnecessary thing, but what I've seen in my
years working on Debian is that enhancing a package's description
correlates to a 30 to 50% increase in users.

A colleague also mentioned that comparing wgrep to this project would be
worthwhile:

  https://github.com/syohex/emacs-helm-ag

For example, I'm guessing wgrep is much faster!

Cheers,
Nicholas

**Comment by mhayashi1120** [comment]
I've pushed changes to the master.

> I'd like it to be resolved before 2020

Sorry again, this late response and unmet your expectation.

Please re-open the issue if something missing to packaging for Debian.

**Comment by sten0** [comment]
Masahiro Hayashi <notifications@github.com> writes:

> I've pushed changes to the master.
>

Thanks!

>> I'd like it to be resolved before 2020
>
> Sorry again, this late response and unmet your expectation.
>

It's ok, we're volunteers :-)  (also, holidays, New Year's, etc)

> Please re-open the issue if something missing to packaging for Debian.

Done.  I opened a PR for what seems to be a missing dependency (it might
also need a "requires"), and I'm also opening a new issue about the
description, because it's hard to tell what wgrep does from its
description.
