### ISSUE TITLE
dead link for the original grep-edit.el

### ISSUE THREAD

**Issue by sten0** [mhayashi1120/Emacs-wgrep#66]
http://www.bookshelf.jp/elc/grep-edit.el resolves to a 403 FORBIDDEN error.  If there isn't an alternative link for Matsushita Akihisa's original version, maybe https://www.emacswiki.org/emacs/grep-edit.el or https://github.com/emacsmirror/emacswiki.org/blob/master/grep-edit.el could be used?

**Comment by mhayashi1120** [comment]
I found original grep-edit.el version 2.11 from my old local repository (Subversion).

> grep-edit.el,v 2.11 2009-10-20 12:12:55 akihisa

I created --orphan branch to download the original source. At new branch `import-original-author` .
