### ISSUE TITLE
Does not work on windows encoded files.

### ISSUE THREAD

**Issue by dinkonin** [mhayashi1120/Emacs-wgrep#68]
When I edit a file with windows CRLF line endings (^M), `wgrep-finish-edit` always displays `There are XX unapplied changes.` and it does nothing. It works If I convert it to unix LF with `set-buffer-file-coding-system` and save it. 

Maybe I'm missing something in the config. Using emacs 26.3 on Arch linux.

**Comment by mhayashi1120** [comment]
DOS newline working well on my environment. What message is displayed in echo area when cursor to the error line?

**Comment by dinkonin** [comment]
There are no errors only `There are XX unapplied changes.` tried with  `toggle-debug-on-error` and it does not trigger.

**Comment by mhayashi1120** [comment]
Hmm, I couldn't see anything. Please try `emacs -q` if you have not.

**Comment by dinkonin** [comment]
Same results with emacs -q . But the problem disappeared when I upgraded to emacs 27.
