### ISSUE TITLE
ack-and-a-half is gone, wgrep-ack is useless

### ISSUE THREAD

**Issue by dod38fr** [mhayashi1120/Emacs-wgrep#91]
Hi

`ack-and-a-half` package is gone (see https://www.emacswiki.org/emacs/Ack).

Could you update wgrep-ack to work with `ack` or `full-ack` ?

All the best

**Comment by c-alpha** [comment]
Hello @dod38fr, I just installed `wgrep` 3.0.0 and `wgrep-ack` works as expected for me with this config:
```elisp
;; https://github.com/leoliu/ack-el
(use-package ack
  :ensure t
  :custom
  (ack-vc-grep-commands nil))

;; https://github.com/mhayashi1120/Emacs-wgrep
(use-package wgrep-ack
  :ensure wgrep
  :after ack
  :custom
  (wgrep-enable-key "e")
  (wgrep-auto-save-buffer t)
  (wgrep-change-readonly-file t))
```

Could you perhaps shed any more light on how `wgrep-ack` does not work as expected?

**Comment by dod38fr** [comment]
Actually, I no longer have this issue with `wgrep` (or I don't remember how to reproduce it...).

Let's close this issue.

Thanks for the help.
